# Generated by Django 5.2.7 on 2025-10-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in dollars (0.00 for free)', max_digits=10),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message to the donor', null=True)),
                ('contact_info', models.CharField(help_text='Phone or email for contact', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='foodshare.foodpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'food_post')},
            },
        ),
    ]
