# Generated by Django 5.2.7 on 2025-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0002_foodpost_is_available_foodpost_price_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in Rupees (0.00 for free)', max_digits=10),
        ),
    ]
